[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[dev]
  targetPort = 5173
  port = 8888

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "max-age=0, no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "max-age=31536000, public"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "max-age=31536000, public"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "max-age=31536000, public"
